# 应用服务 WEB 访问端口, gateway 也会注册到 nacos 上
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      routes:
        - id: oj-judge-service
          uri: lb://oj-judge-service
          predicates:
            - Path=/api/judge/**
        - id: oj-problem-service
          uri: lb://oj-problem-service
          predicates:
            - Path=/api/problem/**
        - id: oj-user-service
          uri: lb://oj-user-service
          predicates:
            - Path=/api/user/**
  application:
    name: oj-gateway
  main:
    web-application-type: reactive
server:
  port: 8101
knife4j:
  gateway:
    # 开启gateway聚合组件
    enabled: true
    # 设置聚合模式采用discover服务发现的模式
    strategy: discover
    discover:
      # 开启discover模式
      enabled: true
      # 聚合子服务全部为Swagger2规范的文档
      version: swagger2